# Generated by Django 5.2.7 on 2025-10-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_slug_alter_course_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('video', 'Видео'), ('text', 'Текст'), ('pdf', 'PDF документ')], max_length=20),
        ),
    ]
