# Generated by Django 5.2.7 on 2025-10-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_lesson_lesson_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='lesson_pdfs/'),
        ),
    ]
