# Generated by Django 5.2.7 on 2026-02-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_question_answer_quiz_question_quiz_quizattempt_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizattempt',
            options={},
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='lessonprogress',
            name='time_spent_minutes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='points',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
        migrations.AlterField(
            model_name='course',
            name='requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='what_you_learn',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=True, help_text='За видео лекции, внесете минимум 500 зборови.'),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='passing_score',
            field=models.PositiveIntegerField(default=70),
        ),
    ]
